#ifndef LOGGINGCATEGORIES_H
#define LOGGINGCATEGORIES_H

#include <QLoggingCategory>
Q_DECLARE_LOGGING_CATEGORY(archiveHTTP)
Q_DECLARE_LOGGING_CATEGORY(archiveSF)
Q_DECLARE_LOGGING_CATEGORY(demo)
Q_DECLARE_LOGGING_CATEGORY(environment)
Q_DECLARE_LOGGING_CATEGORY(epics3)

#endif // LOGGINGCATEGORIES_H
